## Import

In [1]:
from datasets import load_dataset
import pandas as pd

## Dataset

In [ ]:
dataset = load_dataset("arbml/MArSum")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
dataset

DatasetDict({
    test: Dataset({
        features: ['text', 'summary'],
        num_rows: 1981
    })
})

In [4]:
sample = dataset["test"][0]

print("TEXT:")
print(sample["text"])

print("\n" + "=" * 80 + "\n")

print("SUMMARY:")
print(sample["summary"])

TEXT:
أكدت جمهورية كوريا دعمها لجهود هيأة الأمم المتحدة للتوصل إلى حل سياسي لقضية الصحراء. وقد اعترفت كوريا بجهود المغرب لإيجاد حل للنزاع حول الصحراء المغربية. كما رحبت جمهورية كوريا بعودة المغرب إلى منظمة الاتحاد الإفريقي، وبإمكانية انضمامه للمجموعة الاقتصادية لغرب إفريقيا (إيكواس). واعتبر الوزير الأول الكوري بالنموذج المغربي، في لقاء جمعه بنظيره سعد الدين العثماني، أن عودة المغرب هاته، خاصة بالنظر إلى السياسة الإفريقية التي يعتمدها المغرب في ظل التوجيهات الملكية للملك محمد السادس، تشكل خطوة أساسية لضمان الاندماج والاستقرار والتنمية في إفريقيا.

================================================================================

SUMMARY:
كوريا داعمة المغرب على الصحرا ديالو

In [5]:
df = dataset["test"].to_pandas()

df.head()

,text,summary
0,أكدت جمهورية كوريا دعمها لجهود هيأة الأمم المت...,كوريا داعمة المغرب على الصحرا ديالو
1,الرابور عمر السهيلي المعروف بديزي دروس حط فيدي...,بعد الاتهامات بالشفرة.. ديزي دروس تلاقا بالنور...
2,أطاحت عملية مراقبة روتينية بالسد القضائي في مد...,نواحي صفرو.. بالصدفة طاحت عصابة موالفة كتشفر ا...
3,شي كمامر ما كيحشموش. بحال سعيدة شرف. طالعة واك...,ما كتحشمش. اش من ضرائب كتخلص. سعيدة شرف غرقات ...
4,“ناتاشا ابونتي natasha aponte” هي مانكان امري...,هادي الي عبرات. مريكانية دارت رونديفو مع اكثر ...

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1981 entries, 0 to 1980
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     1981 non-null   str
 1   summary  1981 non-null   str
dtypes: str(2)
memory usage: 3.2 MB

In [7]:
for i in range(3):
    print(f"\n{'='*100}")
    print(f"EXAMPLE {i+1}")
    print(f"{'='*100}")

    print("\nTEXT:")
    print(df.iloc[i]["text"])

    print("\nSUMMARY:")
    print(df.iloc[i]["summary"])

====================================================================================================
EXAMPLE 1
====================================================================================================

TEXT:
أكدت جمهورية كوريا دعمها لجهود هيأة الأمم المتحدة للتوصل إلى حل سياسي لقضية الصحراء. وقد اعترفت كوريا بجهود المغرب لإيجاد حل للنزاع حول الصحراء المغربية. كما رحبت جمهورية كوريا بعودة المغرب إلى منظمة الاتحاد الإفريقي، وبإمكانية انضمامه للمجموعة الاقتصادية لغرب إفريقيا (إيكواس). واعتبر الوزير الأول الكوري بالنموذج المغربي، في لقاء جمعه بنظيره سعد الدين العثماني، أن عودة المغرب هاته، خاصة بالنظر إلى السياسة الإفريقية التي يعتمدها المغرب في ظل التوجيهات الملكية للملك محمد السادس، تشكل خطوة أساسية لضمان الاندماج والاستقرار والتنمية في إفريقيا.

SUMMARY:
كوريا داعمة المغرب على الصحرا ديالو

====================================================================================================
EXAMPLE 2
====================================================================================================

TEXT:
الرابور عمر السهيلي المعروف بديزي دروس حط فيديو عبر خاصية الستوزي فانستگرام ديالو، بان فيه انه تلاقا البارح الاثنين مع الفنان المشهور بلقب “النورس” في فرانسا. هاد اللقاء هو تأكيد أن العافية لي شاعلة بيناتهم طفات بعدما توجهو اتهامات لديزي دروس بالشفرة. واحد الجملة استعملها النورس في ديسك قديم ديالو وهو “كينكستر عربي”، وخداها ليه ودارها في أغنيتو الأخيرة “air max”. الجمهور كان طلب من النورس يجاوب ديزي ويكلاشيه حيت خدا ليه كلامو، لكن هو رفض واعتبر الأمر تكريم كثر منو شفرة ومبغاش يدخل معاه في الحرب، لأن الأمر كيدخل فاللعبة ديال الراب. واللي ما كيعرفش النورس هو مول أغنية جينيريك مسلسل ساعة فالجحيم، وأغنية مسلسل وعدي، وهو اللي صوب مع البيگ ألبوم مغاربة حتى لموت، وزيد وزيد…

SUMMARY:
بعد الاتهامات بالشفرة.. ديزي دروس تلاقا بالنورس وطفات العافية

====================================================================================================
EXAMPLE 3
====================================================================================================

TEXT:
أطاحت عملية مراقبة روتينية بالسد القضائي في مدخل مدينة صفرو بعصابة متخصصة في سرقة ضيعة ملكية بنواحي الإقليم. وقالت المصادر لـ”كَود” إن عناصر الشرطة أوقفوا سيارة كانت بصدد الدخول إلى المدينة وعلى متنها 4 أشخاص. وقامت عناصر الأمن بعملية تفتيش السيارة والأشخاص، فعثروا بحوزة أحدهم على سلاح أبيض من الحجم الكبير عبارة عن “سيف”. وتبين، من خلال البحث معهم، أن هؤلاء الأشخاص يشكلون عصابة متخصصة في سرقة ضيعة ملكية بنواحي إقليم صفرو، حيث كانوا يسرقون بعض ثمارها، بتواطؤ مع حارس الضيعة والذي تم توقيفه بدوره. وقالت المصادر نفسها لـ”كَود” بأن النيابة العامة بمحكمة الاستئناف بفاس أمرت بوضع الموقوفين، أمس الأحد، تحت الحراسة النظرية لفائدة البحث، في انتظار تقديمهم أمامها لاتخاذ المتعين قانونا.

SUMMARY:
نواحي صفرو.. بالصدفة طاحت عصابة موالفة كتشفر الفاكية من فيرمة ملكية

In [8]:
benchmark_df = df.sample(
    n=200,
    random_state=42
).reset_index(drop=True)

In [9]:
benchmark_df.head()

,text,summary
0,حلت أمس الإثنين عناصر من الفرقة الوطنية للشرطة...,اختلالات مشروع “كُورْنِيشْ آسفي”.. الفرقة الوط...
1,علمت “كود” ان ندوة الرؤساء بمجلس المستشارين ال...,نايضة على بنشماس على لفلوس عاود ثاني . علاش كن...
2,فالمغرب عارفين ومتأكدين باللي هاد القضية ديال ...,باش التقاليد كتغلب الجايحة. لمغاربة كيزورو وحد...
3,قالت مصادر محلية، أن لجنة تفتيش من وزارة الداخ...,لجنة تفتيشية من الداخلية طارت لجماعات فإقليم ا...
4,قالت صفحة “اسرائيل تتكلم بالعربية”على “الفايسب...,اسرائيل لاعبة كبير وبالزربة مع المغرب. سفيرها ...

## Benchmark

In [ ]:
benchmark_df.to_csv(
    "data/benchmark/arabic_summarization_benchmark.csv",
    index=False,
    encoding="utf-8-sig"
)

In [11]:
print("Missing text:", benchmark_df["text"].isna().sum())
print("Missing summaries:", benchmark_df["summary"].isna().sum())

Missing text: 0
Missing summaries: 0

In [12]:
print("Empty texts:",
      (benchmark_df["text"].str.strip() == "").sum())

print("Empty summaries:",
      (benchmark_df["summary"].str.strip() == "").sum())

Empty texts: 0
Empty summaries: 0